name: build sub-store-workers

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Environment Variables and Install Dependencies
        env:
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          D_TOKEN: ${{ secrets.D_TOKEN }}
        run: |
          sed -i "s|substore_workers_database_name|$DATABASE_NAME|g" wrangler.toml
          sed -i "s|substore_workers_database_id|$DATABASE_ID|g" wrangler.toml
          sed -i "s|substore_workers_bearer_token|$BEARER_TOKEN|g" wrangler.toml
          sed -i "s|substore_workers_d_token|$D_TOKEN|g" wrangler.toml
          pnpm install
          cat wrangler.toml

      - name: Deploy to Cloudflare Workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          pnpm wrangler deploy
